<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsmattermost-duo-test-yenherokuappcom</name>
   <tag></tag>
   <elementGuidId>f57a2468-3375-4ff3-a299-2becc33ca61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js_n0']/div/div/div[2]/div/div/div/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mattermost-duo-test-yen.herokuapp.com/?fbclid=IwAR3ThZZ-3TXckXl-OGcm_8yhbwJJqVBpT4Fycu8gT4BQSBReHB5FyM7rxp0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow noopener</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lynx-mode</name>
      <type>Main</type>
      <value>hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lynx-uri</name>
      <type>Main</type>
      <value>https://l.facebook.com/l.php?u=https%3A%2F%2Fmattermost-duo-test-yen.herokuapp.com%2F%3Ffbclid%3DIwAR3ThZZ-3TXckXl-OGcm_8yhbwJJqVBpT4Fycu8gT4BQSBReHB5FyM7rxp0&amp;h=AT1yLCZVBRKfc_QDaTFcYULSvW5mo17a6IDl8j7_6S8bfKesq6U_xeCus9i-SMK1F1xqafIwZGI_LmGHcWZY-yZ8xIx5MH_hAIYNOxNpdfCSnvo1ZDV71dHbI3dAhE3HOBTPfw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://mattermost-duo-test-yen.herokuapp.com/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_n0&quot;)/div[@class=&quot;_1e-x _n4o&quot;]/div[@class=&quot;_3_bl&quot;]/div[@class=&quot;_5w1r _3_om _5wdf&quot;]/div[@class=&quot;_4gx_&quot;]/div[@class=&quot;_1aa6&quot;]/div[1]/span[@class=&quot;_5yl5&quot;]/span[1]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js_n0']/div/div/div[2]/div/div/div/span/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://mattermost-duo-test-yen.herokuapp.com/')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='j2uu45'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mai mấy h sáng mình làm nốt cái stat lun nhe'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lephamngocyen@gmail.com'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ngocyen'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://mattermost-duo-test-yen.herokuapp.com/']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mattermost-duo-test-yen.herokuapp.com/?fbclid=IwAR3ThZZ-3TXckXl-OGcm_8yhbwJJqVBpT4Fycu8gT4BQSBReHB5FyM7rxp0')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div/div[2]/div/div/div/span/span/a</value>
   </webElementXpaths>
</WebElementEntity>
